### ISSUE TITLE
增加彻底卸载功能

### ISSUE THREAD

**Issue by Vndroid** [benzBrake/ShortLinks#10]
禁用插件的同时删除数据表（默认禁用），满足强迫症用户。

**Comment by benzBrake** [comment]
可以是可以，就是你的选项排序有点神奇，不应该放最后么这种参数

**Comment by Vndroid** [comment]
> 可以是可以，就是你的选项排序有点神奇，不应该放最后么这种参数

最初是想放在最后了，结果发现后面的几个输入框都太大，会遮挡住。最开头也不是很合适，就拆分放中间。
