### ISSUE TITLE
提个新功能

### ISSUE THREAD

**Issue by dyt5AAUI** [benzBrake/ShortLinks#13]
能不能增加附件下载的单页引导功能。或者已有其他插件中增加。

**Comment by benzBrake** [comment]
我的收费插件支持附件单页引导功能，还没发布

**Comment by dyt5AAUI** [comment]
是附件下载增强嘛，我想把全站维护和这个一套买了。

**Comment by benzBrake** [comment]
对，是这个插件，你可以过去看看

**Comment by benzBrake** [comment]
后台自助添加域名授权功能已经弄好了，目前只能买Maintain，AccessoriesPro还在雕琢

**Comment by dyt5AAUI** [comment]
域名授权有啥规则啊

**Comment by benzBrake** [comment]
默认2个域名，更多联系我添加
