### ISSUE TITLE
可以适配一下vditor编辑器么

### ISSUE THREAD

**Issue by FeiYuab** [benzBrake/ShortLinks#15]
使用vditor编辑器 可能因为链接语法不一样 
插件不能自动替换外链
可以解决一下么

**Comment by benzBrake** [comment]
你开启了前台渲染？所有前台渲染的插件都与 ShortLinks 不兼容，目前没有时间适配这类插件

**Comment by yinzsw** [comment]
链接没有自动转换

**Comment by benzBrake** [comment]
fixed in latest version
