### ISSUE TITLE
Plugin.php多了一行

### ISSUE THREAD

**Issue by chengs2035** [benzBrake/ShortLinks#17]
Typecho_Plugin::factory('Widget_Abstract_Comments')->contentEx = array('ShortLinks_Plugin', 'replace');
另外我机器上测试，依旧会报错呀。
replace方法里面
```
@preg_match_all('/<a(.*?)href="(.*?)"(.*?)>/', $text, $matches);
```
还是应该加上是否是array的判断。

**Comment by chengs2035** [comment]
@preg_match_all('/<a(.*?)href="(.*?)"(.*?)>/', $text['text'], $matches);
我目前是这样解决的。

**Comment by benzBrake** [comment]
`Widget_Abstract_Comments`也就是评论也有转换需求的，有人把typecho改造成论坛就用的到了。
还有我这边确实没有报错，你列出一下你用的插件和主题

**Comment by chengs2035** [comment]
> `Widget_Abstract_Comments`也就是评论也有转换需求的，有人把typecho改造成论坛就用的到了。
> 还有我这边确实没有报错，你列出一下你用的插件和主题

有开一个redis缓存，不知道跟这个有没有关系。

```
preg_match_all(): Argument #2 ($subject) must be of type string, array given 
```

![2021-01-09_22-04](https://user-images.githubusercontent.com/12379446/104093642-b9415180-52c6-11eb-84de-648d3e21e513.png)
大概是这些插件，主题是默认的主题。

**Comment by benzBrake** [comment]
诡异了，我装了插件也没有问题，翻源码确然传过来的都是非 array，你确认升级到1.1.0 b3 了吗

> https://github.com/typecho/typecho/blob/834e4722a0f51582e72c5d8a4d2d0f53d4a91a0e/var/Widget/Abstract/Contents.php#L141
>
> https://github.com/typecho/typecho/blob/834e4722a0f51582e72c5d8a4d2d0f53d4a91a0e/var/Widget/Abstract/Contents.php#L119
>
> https://github.com/typecho/typecho/blob/834e4722a0f51582e72c5d8a4d2d0f53d4a91a0e/var/Widget/Abstract/Comments.php#L119

**Comment by chengs2035** [comment]
我没有用最新的typecho，还是用的最后发布的稳定版， 版本 1.1 (17.10.30) 
不知道跟这个有没有关系。。。

**Comment by chengs2035** [comment]
现在多了一个**Typecho_Date**的错误。。。
```

Object of class Typecho_Date could not be converted to string
Error: Object of class Typecho_Date could not be converted to string in /var/www/html/usr/plugins/ShortLinks/Plugin.php:173
Stack trace:
#0 /var/www/html/usr/plugins/ShortLinks/Plugin.php(173): str_replace('href="http://en...', 'href="https://w...', Array)
#1 /var/www/html/var/Typecho/Plugin.php(489): ShortLinks_Plugin::replace(Array, Object(Widget_Archive), NULL)
#2 /var/www/html/var/Widget/Abstract/Contents.php(733): Typecho_Plugin->__call('Widget_Abstract...', Array)
#3 /var/www/html/var/Widget/Abstract/Contents.php(761): Widget_Abstract_Contents->filter(Array)
#4 /var/www/html/var/Typecho/Db.php(395): Widget_Abstract_Contents->push(Array)
#5 /var/www/html/var/Widget/Archive.php(1250): Typecho_Db->fetchAll(Object(Typecho_Db_Query), Array)
#6 /var/www/html/var/Widget/Archive.php(1392): Widget_Archive->query(Object(Typecho_Db_Query))
#7 /var/www/html/var/Typecho/Widget.php(221): Widget_Archive->execute()
#8 /var/www/html/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Archive', NULL, Array)
#9 /var/www/html/index.php(23): Typecho_Router::dispatch()
#10 {main}
```

**Comment by chengs2035** [comment]
我打印了$text，大佬帮我看下这个。。。的确是array

![2021-01-10_23-11](https://user-images.githubusercontent.com/12379446/104126745-4359ea80-5399-11eb-91eb-2f0121eb15d9.png)

**Comment by benzBrake** [comment]
我是说你 Shortlinks 是用的最新版么，我无法重现，我建议你尝试升级Typecho，稳定版是存在安全漏洞的
https://github.com/typecho/typecho/issues/845

**Comment by chengs2035** [comment]
> 我是说你 Shortlinks 是用的最新版么，我无法重现，我建议你尝试升级Typecho，稳定版是存在安全漏洞的
> [typecho/typecho#845](https://github.com/typecho/typecho/issues/845)

Shortlinks是最新的，我最近没遇到报错，是用了isarray的判断。
我现在怀疑可能性是：
1. 升级Shortlinks的时候，没有先停用插件
2. 以前我的编辑器是用UEDIT，后来换到MARKDOWN上了，估计是有啥奇怪的字符混进去了。
3. 跟tpcache插件不知道有没有冲突
如果下个月还是这样，那就close 掉咯。。。
至于升级typecho，我一直在等着正式版。。。好几年了。
