### ISSUE TITLE
启用错误

### ISSUE THREAD

**Issue by uitcis** [benzBrake/ShortLinks#22]
Too few arguments to function Typecho_Db::getConfig(), 0 passed in /www/wwwroot/TY.PECHO/usr/plugins/ShortLinks/Plugin.php on line 33 and exactly 1 expected

**Comment by benzBrake** [comment]
你得说一下环境让我复现问题 比如 Te 版本， PHP 版本

**Comment by benzBrake** [comment]
你用的 Typecho 1.2 吧，最新版修复这个问题了
