### ISSUE TITLE
短链管理空白

### ISSUE THREAD

**Issue by oyh196** [benzBrake/ShortLinks#25]
typecho升级1.2后短链管理的怎搞的打开后是空白页面

**Comment by benzBrake** [comment]
master 最新版没这个问题，你升级一下

**Comment by oyh196** [comment]
插件版本是1.2.0 b1  还是空白

**Comment by benzBrake** [comment]
无法复现，你打开 Typecho 的 Debug 模式，看看有什么报错，提供一下系统/PHP 版本
![短链管理](https://user-images.githubusercontent.com/11323774/161410487-a0049741-0a0c-411b-8d19-6d5b9137ac4e.jpg)

**Comment by oyh196** [comment]
sorry是我自己的问题，打扰了不好意思。
