### ISSUE TITLE
启用伪静态和固定链接后插件无法工作

### ISSUE THREAD

**Issue by TacKana** [benzBrake/ShortLinks#31]
设置伪静态和固定链接后安装插件无法启用插件，404

**Comment by benzBrake** [comment]
你这种报告是没有意义的，一点参考的东西都没有

**Comment by TacKana** [comment]
不好意思，发错了，提交iss的时候没注意看浏览器标签，我这就关闭



---原始邮件---
发件人: "Ryan ***@***.***&gt;
发送时间: 2024年4月10日(周三) 晚上7:38
收件人: ***@***.***&gt;;
抄送: "new ***@***.******@***.***&gt;;
主题: Re: [benzBrake/ShortLinks] 启用伪静态和固定链接后插件无法工作 (Issue #31)




 
你这种报告是没有意义的，一点参考的东西都没有
